development:
  adapter: postgresql
  database: trustease_database_development
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: trustease_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: trustease_database_production
  pool: 5
  timeout: 5000
